
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://whspcnovvaqeztgtcsjl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Indoc3Bjbm92dmFxZXp0Z3Rjc2psIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDExNDI0MDUsImV4cCI6MjA1NjcxODQwNX0.dadXKAcGccwgVwrBcwEpDp5jeQRo5w-_A4z_MmbrbFo";

// Create Supabase client with enhanced error handling
export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    autoRefreshToken: true,
    persistSession: true,
    detectSessionInUrl: true
  },
  global: {
    headers: {
      'X-Client-Info': 'allerpaws-app'
    }
  }
});

// Add a helper function to check if an error is a Row Level Security error
export const isRLSError = (error: any): boolean => {
  return error?.message?.includes('row-level security') || 
         error?.code === 'PGRST301' || 
         error?.code === '42501';
};

// Helper function to safely access properties from potentially error objects
export function safelyUnwrapResult<T>(result: T | { error: true } & Error): T | null {
  if (result && typeof result === 'object' && 'error' in result && result.error === true) {
    console.error('Error in Supabase result:', result);
    return null;
  }
  return result as T;
}

// Helper function to map database rows to application types
export function mapDbRowsToAppTypes<T>(data: any, mapper: (row: any) => T): T[] {
  if (!data || !Array.isArray(data)) return [];
  return data.map(mapper);
}

// Helper function to safely unwrap a single result
export function unwrapSingleResult<T>(result: T | { error: true } & Error): T | null {
  if (result && typeof result === 'object' && 'error' in result && result.error === true) {
    console.error('Error in Supabase single result:', result);
    return null;
  }
  return result as T;
}

// Type guard to check if a result is an error
export function isQueryError(result: any): result is { error: true } & Error {
  return result && typeof result === 'object' && 'error' in result && result.error === true;
}
